// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: foo.sql

package db

import (
	"context"
)

const createFoo = `-- name: CreateFoo :one
INSERT INTO foos (
  message
) VALUES (
  $1
)
RETURNING id, message, created_at, updated_at, deleted_at
`

func (q *Queries) CreateFoo(ctx context.Context, message string) (Foo, error) {
	row := q.db.QueryRow(ctx, createFoo, message)
	var i Foo
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getFoo = `-- name: GetFoo :one
SELECT id, message, created_at, updated_at, deleted_at FROM foos
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetFoo(ctx context.Context, id int32) (Foo, error) {
	row := q.db.QueryRow(ctx, getFoo, id)
	var i Foo
	err := row.Scan(
		&i.ID,
		&i.Message,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
