// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Foo struct {
	ID        int32
	Message   string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	DeletedAt pgtype.Timestamp
}

type User struct {
	ID            string
	LookupID      string
	Email         string
	PasswordHash  string
	Secret        string
	Name          string
	Role          string
	AvatarUrl     string
	Provider      string
	ProviderID    string
	EmailVerified bool
	Disabled      bool
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}
