// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT id, lookup_id, email, password_hash, secret, name, role, avatar_url, provider, provider_id, email_verified, disabled, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.LookupID,
		&i.Email,
		&i.PasswordHash,
		&i.Secret,
		&i.Name,
		&i.Role,
		&i.AvatarUrl,
		&i.Provider,
		&i.ProviderID,
		&i.EmailVerified,
		&i.Disabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
